export const PGC_BASICO = [
    // GRUPO 1: FINANCIACIÓN BÁSICA
    { codigo: '100', nombre: 'Capital social' },
    { codigo: '101', nombre: 'Fondo social' },
    { codigo: '102', nombre: 'Capital' },
    { codigo: '103', nombre: 'Socios por desembolsos no exigidos' },
    { codigo: '104', nombre: 'Socios por aportaciones no dinerarias pendientes' },
    { codigo: '108', nombre: 'Acciones o participaciones propias en situaciones especiales' },
    { codigo: '109', nombre: 'Acciones o participaciones propias para reducción de capital' },
    { codigo: '110', nombre: 'Prima de emisión o asunción' },
    { codigo: '111', nombre: 'Otros instrumentos de patrimonio neto' },
    { codigo: '112', nombre: 'Reserva legal' },
    { codigo: '113', nombre: 'Reservas voluntarias' },
    { codigo: '114', nombre: 'Reservas especiales' },
    { codigo: '115', nombre: 'Reservas por pérdidas y ganancias actuariales' },
    { codigo: '118', nombre: 'Aportaciones de socios o propietarios' },
    { codigo: '119', nombre: 'Diferencias por ajuste del capital a euros' },
    { codigo: '120', nombre: 'Remanente' },
    { codigo: '121', nombre: 'Resultados negativos de ejercicios anteriores' },
    { codigo: '129', nombre: 'Resultado del ejercicio' },
    { codigo: '130', nombre: 'Subvenciones oficiales de capital' },
    { codigo: '131', nombre: 'Donaciones y legados de capital' },
    { codigo: '132', nombre: 'Otras subvenciones, donaciones y legados' },
    { codigo: '133', nombre: 'Ajustes por valoración en activos financieros a valor razonable' },
    { codigo: '134', nombre: 'Operaciones de cobertura' },
    { codigo: '135', nombre: 'Diferencias de conversión' },
    { codigo: '136', nombre: 'Ajustes por valoración en activos no corrientes' },
    { codigo: '140', nombre: 'Provisiones por retribuciones a largo plazo al personal' },
    { codigo: '141', nombre: 'Provisión para impuestos' },
    { codigo: '142', nombre: 'Provisión para otras responsabilidades' },
    { codigo: '143', nombre: 'Provisión por desmantelamiento, retiro o rehabilitación' },
    { codigo: '145', nombre: 'Provisión para actuaciones medioambientales' },
    { codigo: '146', nombre: 'Provisión para reestructuraciones' },
    { codigo: '147', nombre: 'Provisión por transacciones con pagos basados en instrumentos de patrimonio' },
    { codigo: '150', nombre: 'Acciones o participaciones a largo plazo consideradas como pasivos financieros' },
    { codigo: '153', nombre: 'Desembolsos no exigidos por acciones o participaciones consideradas como pasivos' },
    { codigo: '154', nombre: 'Aportaciones no dinerarias pendientes por acciones consideradas como pasivos' },
    { codigo: '160', nombre: 'Deudas a largo plazo con entidades de crédito vinculadas' },
    { codigo: '161', nombre: 'Proveedores de inmovilizado a largo plazo, partes vinculadas' },
    { codigo: '162', nombre: 'Acreedores por arrendamiento financiero a largo plazo, partes vinculadas' },
    { codigo: '163', nombre: 'Otras deudas a largo plazo con partes vinculadas' },
    { codigo: '170', nombre: 'Deudas a largo plazo con entidades de crédito' },
    { codigo: '171', nombre: 'Deudas a largo plazo' },
    { codigo: '172', nombre: 'Deudas a largo plazo transformables en subvenciones' },
    { codigo: '173', nombre: 'Proveedores de inmovilizado a largo plazo' },
    { codigo: '174', nombre: 'Acreedores por arrendamiento financiero a largo plazo' },
    { codigo: '175', nombre: 'Efectos a pagar a largo plazo' },
    { codigo: '176', nombre: 'Pasivos por derivados financieros a largo plazo' },
    { codigo: '177', nombre: 'Obligaciones y bonos' },
    { codigo: '178', nombre: 'Obligaciones y bonos convertibles' },
    { codigo: '179', nombre: 'Deudas representadas en otros valores negociables' },
    { codigo: '180', nombre: 'Fianzas recibidas a largo plazo' },
    { codigo: '181', nombre: 'Anticipos recibidos por ventas o prestaciones de servicios a largo plazo' },
    { codigo: '185', nombre: 'Depósitos recibidos a largo plazo' },
    { codigo: '189', nombre: 'Garantías financieras a largo plazo' },
    { codigo: '190', nombre: 'Acciones o participaciones emitidas' },
    { codigo: '192', nombre: 'Suscriptores de acciones' },
    { codigo: '194', nombre: 'Capital emitido pendiente de inscripción' },
    { codigo: '195', nombre: 'Acciones o participaciones emitidas consideradas como pasivos financieros' },
    { codigo: '197', nombre: 'Suscriptores de acciones consideradas como pasivos financieros' },
    { codigo: '199', nombre: 'Acciones o participaciones emitidas consideradas como pasivos financieros pendientes de inscripción' },

    // GRUPO 2: ACTIVO NO CORRIENTE
    { codigo: '200', nombre: 'Investigación' },
    { codigo: '201', nombre: 'Desarrollo' },
    { codigo: '202', nombre: 'Concesiones administrativas' },
    { codigo: '203', nombre: 'Propiedad industrial' },
    { codigo: '204', nombre: 'Fondo de comercio' },
    { codigo: '205', nombre: 'Derechos de traspaso' },
    { codigo: '206', nombre: 'Aplicaciones informáticas' },
    { codigo: '209', nombre: 'Anticipos para inmovilizaciones intangibles' },
    { codigo: '210', nombre: 'Terrenos y bienes naturales' },
    { codigo: '211', nombre: 'Construcciones' },
    { codigo: '212', nombre: 'Instalaciones técnicas' },
    { codigo: '213', nombre: 'Maquinaria' },
    { codigo: '214', nombre: 'Utillaje' },
    { codigo: '215', nombre: 'Otras instalaciones' },
    { codigo: '216', nombre: 'Mobiliario' },
    { codigo: '217', nombre: 'Equipos para procesos de información' },
    { codigo: '218', nombre: 'Elementos de transporte' },
    { codigo: '219', nombre: 'Otro inmovilizado material' },
    { codigo: '220', nombre: 'Inversiones en terrenos y bienes naturales' },
    { codigo: '221', nombre: 'Inversiones en construcciones' },
    { codigo: '230', nombre: 'Adaptación de terrenos y bienes naturales' },
    { codigo: '231', nombre: 'Construcciones en curso' },
    { codigo: '232', nombre: 'Instalaciones técnicas en montaje' },
    { codigo: '233', nombre: 'Maquinaria en montaje' },
    { codigo: '237', nombre: 'Equipos para procesos de información en montaje' },
    { codigo: '239', nombre: 'Anticipos para inmovilizaciones materiales' },
    { codigo: '240', nombre: 'Participaciones a largo plazo en partes vinculadas' },
    { codigo: '241', nombre: 'Valores representativos de deuda a largo plazo de partes vinculadas' },
    { codigo: '242', nombre: 'Créditos a largo plazo a partes vinculadas' },
    { codigo: '249', nombre: 'Desembolsos pendientes sobre participaciones a largo plazo en partes vinculadas' },
    { codigo: '250', nombre: 'Inversiones financieras a largo plazo en instrumentos de patrimonio' },
    { codigo: '251', nombre: 'Valores representativos de deuda a largo plazo' },
    { codigo: '252', nombre: 'Créditos a largo plazo' },
    { codigo: '253', nombre: 'Créditos a largo plazo por enajenación de inmovilizado' },
    { codigo: '254', nombre: 'Créditos a largo plazo al personal' },
    { codigo: '255', nombre: 'Activos por derivados financieros a largo plazo' },
    { codigo: '257', nombre: 'Derechos de reembolso derivados de contratos de seguro relativos a retribuciones a largo plazo al personal' },
    { codigo: '258', nombre: 'Imposiciones a largo plazo' },
    { codigo: '259', nombre: 'Desembolsos pendientes sobre participaciones en el patrimonio neto a largo plazo' },
    { codigo: '260', nombre: 'Fianzas constituidas a largo plazo' },
    { codigo: '265', nombre: 'Depósitos constituidos a largo plazo' },
    { codigo: '280', nombre: 'Amortización acumulada del inmovilizado intangible' },
    { codigo: '281', nombre: 'Amortización acumulada del inmovilizado material' },
    { codigo: '282', nombre: 'Amortización acumulada de las inversiones inmobiliarias' },
    { codigo: '290', nombre: 'Deterioro de valor del inmovilizado intangible' },
    { codigo: '291', nombre: 'Deterioro de valor del inmovilizado material' },
    { codigo: '292', nombre: 'Deterioro de valor de las inversiones inmobiliarias' },
    { codigo: '293', nombre: 'Deterioro de valor de participaciones a largo plazo en partes vinculadas' },
    { codigo: '294', nombre: 'Deterioro de valor de valores representativos de deuda a largo plazo de partes vinculadas' },
    { codigo: '295', nombre: 'Deterioro de valor de créditos a largo plazo a partes vinculadas' },
    { codigo: '297', nombre: 'Deterioro de valor de valores representativos de deuda a largo plazo' },
    { codigo: '298', nombre: 'Deterioro de valor de créditos a largo plazo' },

    // GRUPO 3: EXISTENCIAS
    { codigo: '300', nombre: 'Mercaderías A' },
    { codigo: '301', nombre: 'Mercaderías B' },
    { codigo: '310', nombre: 'Materias primas A' },
    { codigo: '311', nombre: 'Materias primas B' },
    { codigo: '320', nombre: 'Elementos y conjuntos incorporables' },
    { codigo: '321', nombre: 'Combustibles' },
    { codigo: '322', nombre: 'Repuestos' },
    { codigo: '325', nombre: 'Materiales diversos' },
    { codigo: '326', nombre: 'Embalajes' },
    { codigo: '327', nombre: 'Envases' },
    { codigo: '328', nombre: 'Material de oficina' },
    { codigo: '330', nombre: 'Productos en curso A' },
    { codigo: '331', nombre: 'Productos en curso B' },
    { codigo: '340', nombre: 'Productos semiterminados A' },
    { codigo: '341', nombre: 'Productos semiterminados B' },
    { codigo: '350', nombre: 'Productos terminados A' },
    { codigo: '351', nombre: 'Productos terminados B' },
    { codigo: '360', nombre: 'Subproductos A' },
    { codigo: '361', nombre: 'Subproductos B' },
    { codigo: '365', nombre: 'Residuos A' },
    { codigo: '366', nombre: 'Residuos B' },
    { codigo: '368', nombre: 'Materiales recuperados A' },
    { codigo: '369', nombre: 'Materiales recuperados B' },
    { codigo: '390', nombre: 'Deterioro de valor de las mercaderías' },
    { codigo: '391', nombre: 'Deterioro de valor de las materias primas' },
    { codigo: '392', nombre: 'Deterioro de valor de otros aprovisionamientos' },
    { codigo: '393', nombre: 'Deterioro de valor de los productos en curso' },
    { codigo: '394', nombre: 'Deterioro de valor de los productos semiterminados' },
    { codigo: '395', nombre: 'Deterioro de valor de los productos terminados' },
    { codigo: '396', nombre: 'Deterioro de valor de los subproductos, residuos y materiales recuperados' },

    // GRUPO 4: ACREEDORES Y DEUDORES POR OPERACIONES COMERCIALES
    { codigo: '400', nombre: 'Proveedores' },
    { codigo: '401', nombre: 'Proveedores, efectos comerciales a pagar' },
    { codigo: '403', nombre: 'Proveedores, empresas del grupo' },
    { codigo: '404', nombre: 'Proveedores, empresas asociadas' },
    { codigo: '405', nombre: 'Proveedores, otras partes vinculadas' },
    { codigo: '406', nombre: 'Envases y embalajes a devolver a proveedores' },
    { codigo: '407', nombre: 'Anticipos a proveedores' },
    { codigo: '410', nombre: 'Acreedores por prestaciones de servicios' },
    { codigo: '411', nombre: 'Acreedores, efectos comerciales a pagar' },
    { codigo: '419', nombre: 'Acreedores por operaciones en común' },
    { codigo: '430', nombre: 'Clientes' },
    { codigo: '431', nombre: 'Clientes, efectos comerciales a cobrar' },
    { codigo: '432', nombre: 'Clientes, operaciones de factoring' },
    { codigo: '433', nombre: 'Clientes, empresas del grupo' },
    { codigo: '434', nombre: 'Clientes, empresas asociadas' },
    { codigo: '435', nombre: 'Clientes, otras partes vinculadas' },
    { codigo: '436', nombre: 'Clientes de dudoso cobro' },
    { codigo: '437', nombre: 'Envases y embalajes a devolver por clientes' },
    { codigo: '438', nombre: 'Anticipos de clientes' },
    { codigo: '440', nombre: 'Deudores' },
    { codigo: '441', nombre: 'Deudores, efectos comerciales a cobrar' },
    { codigo: '446', nombre: 'Deudores de dudoso cobro' },
    { codigo: '449', nombre: 'Deudores por operaciones en común' },
    { codigo: '460', nombre: 'Anticipos de remuneraciones' },
    { codigo: '465', nombre: 'Remuneraciones pendientes de pago' },
    { codigo: '466', nombre: 'Remuneraciones mediante sistemas de aportación definida pendientes de pago' },
    { codigo: '470', nombre: 'Hacienda Pública, deudora por diversos conceptos' },
    { codigo: '4700', nombre: 'Hacienda Pública, deudora por IVA' },
    { codigo: '4708', nombre: 'Hacienda Pública, deudora por subvenciones concedidas' },
    { codigo: '4709', nombre: 'Hacienda Pública, deudora por devolución de impuestos' },
    { codigo: '471', nombre: 'Organismos de la Seguridad Social, deudores' },
    { codigo: '472', nombre: 'Hacienda Pública, IVA soportado' },
    { codigo: '473', nombre: 'Hacienda Pública, retenciones y pagos a cuenta' },
    { codigo: '474', nombre: 'Activos por impuesto diferido' },
    { codigo: '475', nombre: 'Hacienda Pública, acreedora por conceptos fiscales' },
    { codigo: '4750', nombre: 'Hacienda Pública, acreedora por IVA' },
    { codigo: '4751', nombre: 'Hacienda Pública, acreedora por retenciones practicadas' },
    { codigo: '4752', nombre: 'Hacienda Pública, acreedora por impuesto sobre sociedades' },
    { codigo: '476', nombre: 'Organismos de la Seguridad Social, acreedores' },
    { codigo: '477', nombre: 'Hacienda Pública, IVA repercutido' },
    { codigo: '479', nombre: 'Pasivos por diferencias temporarias imponibles' },
    { codigo: '480', nombre: 'Gastos anticipados' },
    { codigo: '485', nombre: 'Ingresos anticipados' },
    { codigo: '490', nombre: 'Deterioro de valor de créditos por operaciones comerciales' },
    { codigo: '493', nombre: 'Deterioro de valor de créditos por operaciones comerciales con partes vinculadas' },

    // GRUPO 5: CUENTAS FINANCIERAS
    { codigo: '500', nombre: 'Obligaciones y bonos a corto plazo' },
    { codigo: '505', nombre: 'Deudas representadas en otros valores negociables a corto plazo' },
    { codigo: '509', nombre: 'Valores negociables amortizados' },
    { codigo: '510', nombre: 'Deudas a corto plazo con entidades de crédito vinculadas' },
    { codigo: '511', nombre: 'Proveedores de inmovilizado a corto plazo, partes vinculadas' },
    { codigo: '512', nombre: 'Acreedores por arrendamiento financiero a corto plazo, partes vinculadas' },
    { codigo: '513', nombre: 'Otras deudas a corto plazo con partes vinculadas' },
    { codigo: '514', nombre: 'Intereses a corto plazo de deudas con partes vinculadas' },
    { codigo: '520', nombre: 'Deudas a corto plazo con entidades de crédito' },
    { codigo: '521', nombre: 'Deudas a corto plazo' },
    { codigo: '522', nombre: 'Deudas a corto plazo transformables en subvenciones' },
    { codigo: '523', nombre: 'Proveedores de inmovilizado a corto plazo' },
    { codigo: '524', nombre: 'Acreedores por arrendamiento financiero a corto plazo' },
    { codigo: '525', nombre: 'Efectos a pagar a corto plazo' },
    { codigo: '526', nombre: 'Dividendo activo a pagar' },
    { codigo: '527', nombre: 'Intereses a corto plazo de deudas con entidades de crédito' },
    { codigo: '528', nombre: 'Intereses a corto plazo de deudas' },
    { codigo: '529', nombre: 'Provisiones a corto plazo' },
    { codigo: '530', nombre: 'Participaciones a corto plazo en partes vinculadas' },
    { codigo: '531', nombre: 'Valores representativos de deuda a corto plazo de partes vinculadas' },
    { codigo: '532', nombre: 'Créditos a corto plazo a partes vinculadas' },
    { codigo: '533', nombre: 'Intereses a corto plazo de valores representativos de deuda de partes vinculadas' },
    { codigo: '534', nombre: 'Intereses a corto plazo de créditos a partes vinculadas' },
    { codigo: '535', nombre: 'Dividendo a cobrar de inversiones financieras en partes vinculadas' },
    { codigo: '539', nombre: 'Desembolsos pendientes sobre participaciones a corto plazo en partes vinculadas' },
    { codigo: '540', nombre: 'Inversiones financieras a corto plazo en instrumentos de patrimonio' },
    { codigo: '541', nombre: 'Valores representativos de deuda a corto plazo' },
    { codigo: '542', nombre: 'Créditos a corto plazo' },
    { codigo: '543', nombre: 'Créditos a corto plazo por enajenación de inmovilizado' },
    { codigo: '544', nombre: 'Créditos a corto plazo al personal' },
    { codigo: '545', nombre: 'Dividendo a cobrar' },
    { codigo: '546', nombre: 'Intereses a corto plazo de valores representativos de deuda' },
    { codigo: '547', nombre: 'Intereses a corto plazo de créditos' },
    { codigo: '548', nombre: 'Imposiciones a corto plazo' },
    { codigo: '549', nombre: 'Desembolsos pendientes sobre participaciones en el patrimonio neto a corto plazo' },
    { codigo: '550', nombre: 'Titular de la explotación' },
    { codigo: '551', nombre: 'Cuenta corriente con socios y administradores' },
    { codigo: '552', nombre: 'Cuenta corriente con otras personas y entidades vinculadas' },
    { codigo: '554', nombre: 'Cuenta corriente con uniones temporales de empresas y comunidades de bienes' },
    { codigo: '555', nombre: 'Partidas pendientes de aplicación' },
    { codigo: '556', nombre: 'Desembolsos exigidos sobre participaciones en el patrimonio neto' },
    { codigo: '557', nombre: 'Dividendo activo a cuenta' },
    { codigo: '558', nombre: 'Socios por desembolsos exigidos' },
    { codigo: '559', nombre: 'Derivados financieros a corto plazo' },
    { codigo: '560', nombre: 'Fianzas recibidas a corto plazo' },
    { codigo: '561', nombre: 'Depósitos recibidos a corto plazo' },
    { codigo: '565', nombre: 'Fianzas constituidas a corto plazo' },
    { codigo: '566', nombre: 'Depósitos constituidos a corto plazo' },
    { codigo: '570', nombre: 'Caja, euros' },
    { codigo: '571', nombre: 'Caja, moneda extranjera' },
    { codigo: '572', nombre: 'Bancos e instituciones de crédito c/c vista, euros' },
    { codigo: '573', nombre: 'Bancos e instituciones de crédito c/c vista, moneda extranjera' },
    { codigo: '574', nombre: 'Bancos e instituciones de crédito, cuentas de ahorro, euros' },
    { codigo: '575', nombre: 'Bancos e instituciones de crédito, cuentas de ahorro, moneda extranjera' },
    { codigo: '576', nombre: 'Inversiones a corto plazo de gran liquidez' },
    { codigo: '580', nombre: 'Deterioro de valor de participaciones a corto plazo en partes vinculadas' },
    { codigo: '581', nombre: 'Deterioro de valor de valores representativos de deuda a corto plazo de partes vinculadas' },
    { codigo: '582', nombre: 'Deterioro de valor de créditos a corto plazo a partes vinculadas' },
    { codigo: '593', nombre: 'Deterioro de valor de participaciones a corto plazo en partes vinculadas' },
    { codigo: '594', nombre: 'Deterioro de valor de valores representativos de deuda a corto plazo de partes vinculadas' },
    { codigo: '595', nombre: 'Deterioro de valor de créditos a corto plazo a partes vinculadas' },
    { codigo: '597', nombre: 'Deterioro de valor de valores representativos de deuda a corto plazo' },
    { codigo: '598', nombre: 'Deterioro de valor de créditos a corto plazo' },

    // GRUPO 6: COMPRAS Y GASTOS
    { codigo: '600', nombre: 'Compras de mercaderías' },
    { codigo: '601', nombre: 'Compras de materias primas' },
    { codigo: '602', nombre: 'Compras de otros aprovisionamientos' },
    { codigo: '606', nombre: 'Descuentos sobre compras por pronto pago' },
    { codigo: '607', nombre: 'Trabajos realizados por otras empresas' },
    { codigo: '608', nombre: 'Devoluciones de compras y operaciones similares' },
    { codigo: '609', nombre: 'Rappels por compras' },
    { codigo: '610', nombre: 'Variación de existencias de mercaderías' },
    { codigo: '611', nombre: 'Variación de existencias de materias primas' },
    { codigo: '612', nombre: 'Variación de existencias de otros aprovisionamientos' },
    { codigo: '620', nombre: 'Gastos en investigación y desarrollo del ejercicio' },
    { codigo: '621', nombre: 'Arrendamientos y cánones' },
    { codigo: '622', nombre: 'Reparaciones y conservación' },
    { codigo: '623', nombre: 'Servicios de profesionales independientes' },
    { codigo: '624', nombre: 'Transportes' },
    { codigo: '625', nombre: 'Primas de seguros' },
    { codigo: '626', nombre: 'Servicios bancarios y similares' },
    { codigo: '627', nombre: 'Publicidad, propaganda y relaciones públicas' },
    { codigo: '628', nombre: 'Suministros' },
    { codigo: '629', nombre: 'Otros servicios' },
    { codigo: '630', nombre: 'Impuesto sobre beneficios' },
    { codigo: '631', nombre: 'Otros tributos' },
    { codigo: '633', nombre: 'Ajustes negativos en la imposición sobre beneficios' },
    { codigo: '634', nombre: 'Ajustes negativos en la imposición indirecta' },
    { codigo: '636', nombre: 'Devolución de impuestos' },
    { codigo: '638', nombre: 'Ajustes positivos en la imposición sobre beneficios' },
    { codigo: '639', nombre: 'Ajustes positivos en la imposición indirecta' },
    { codigo: '640', nombre: 'Sueldos y salarios' },
    { codigo: '641', nombre: 'Indemnizaciones' },
    { codigo: '642', nombre: 'Seguridad Social a cargo de la empresa' },
    { codigo: '643', nombre: 'Retribuciones a largo plazo mediante sistemas de aportación definida' },
    { codigo: '644', nombre: 'Retribuciones a largo plazo mediante sistemas de prestación definida' },
    { codigo: '645', nombre: 'Retribuciones al personal mediante instrumentos de patrimonio' },
    { codigo: '649', nombre: 'Otros gastos sociales' },
    { codigo: '650', nombre: 'Pérdidas de créditos comerciales incobrables' },
    { codigo: '651', nombre: 'Resultados de operaciones en común' },
    { codigo: '659', nombre: 'Otras pérdidas en gestión corriente' },
    { codigo: '660', nombre: 'Gastos financieros por actualización de provisiones' },
    { codigo: '661', nombre: 'Intereses de obligaciones y bonos' },
    { codigo: '662', nombre: 'Intereses de deudas' },
    { codigo: '663', nombre: 'Pérdidas por valoración de activos y pasivos financieros por su valor razonable' },
    { codigo: '664', nombre: 'Gastos por dividendos de acciones o participaciones consideradas como pasivos financieros' },
    { codigo: '665', nombre: 'Intereses por descuento de efectos y operaciones de factoring' },
    { codigo: '666', nombre: 'Pérdidas en participaciones y valores representativos de deuda' },
    { codigo: '667', nombre: 'Pérdidas de créditos no comerciales' },
    { codigo: '668', nombre: 'Diferencias negativas de cambio' },
    { codigo: '669', nombre: 'Otros gastos financieros' },
    { codigo: '670', nombre: 'Pérdidas procedentes del inmovilizado intangible' },
    { codigo: '671', nombre: 'Pérdidas procedentes del inmovilizado material' },
    { codigo: '672', nombre: 'Pérdidas procedentes de las inversiones inmobiliarias' },
    { codigo: '673', nombre: 'Pérdidas procedentes de participaciones a largo plazo en partes vinculadas' },
    { codigo: '675', nombre: 'Pérdidas por operaciones con obligaciones propias' },
    { codigo: '678', nombre: 'Gastos excepcionales' },
    { codigo: '680', nombre: 'Amortización del inmovilizado intangible' },
    { codigo: '681', nombre: 'Amortización del inmovilizado material' },
    { codigo: '682', nombre: 'Amortización de las inversiones inmobiliarias' },
    { codigo: '690', nombre: 'Pérdidas por deterioro del inmovilizado intangible' },
    { codigo: '691', nombre: 'Pérdidas por deterioro del inmovilizado material' },
    { codigo: '692', nombre: 'Pérdidas por deterioro de las inversiones inmobiliarias' },
    { codigo: '693', nombre: 'Pérdidas por deterioro de existencias' },
    { codigo: '694', nombre: 'Pérdidas por deterioro de créditos por operaciones comerciales' },
    { codigo: '695', nombre: 'Dotación a la provisión por operaciones comerciales' },
    { codigo: '696', nombre: 'Pérdidas por deterioro de participaciones y valores representativos de deuda a largo plazo' },
    { codigo: '697', nombre: 'Pérdidas por deterioro de créditos a largo plazo' },
    { codigo: '698', nombre: 'Pérdidas por deterioro de participaciones y valores representativos de deuda a corto plazo' },
    { codigo: '699', nombre: 'Pérdidas por deterioro de créditos a corto plazo' },

    // GRUPO 7: VENTAS E INGRESOS
    { codigo: '700', nombre: 'Ventas de mercaderías' },
    { codigo: '701', nombre: 'Ventas de productos terminados' },
    { codigo: '702', nombre: 'Ventas de productos semiterminados' },
    { codigo: '703', nombre: 'Ventas de subproductos y residuos' },
    { codigo: '704', nombre: 'Ventas de envases y embalajes' },
    { codigo: '705', nombre: 'Prestaciones de servicios' },
    { codigo: '706', nombre: 'Descuentos sobre ventas por pronto pago' },
    { codigo: '708', nombre: 'Devoluciones de ventas y operaciones similares' },
    { codigo: '709', nombre: 'Rappels sobre ventas' },
    { codigo: '710', nombre: 'Variación de existencias de productos en curso' },
    { codigo: '711', nombre: 'Variación de existencias de productos semiterminados' },
    { codigo: '712', nombre: 'Variación de existencias de productos terminados' },
    { codigo: '713', nombre: 'Variación de existencias de subproductos, residuos y materiales recuperados' },
    { codigo: '730', nombre: 'Trabajos realizados para el inmovilizado intangible' },
    { codigo: '731', nombre: 'Trabajos realizados para el inmovilizado material' },
    { codigo: '732', nombre: 'Trabajos realizados en inversiones inmobiliarias' },
    { codigo: '733', nombre: 'Trabajos realizados para el inmovilizado material en curso' },
    { codigo: '740', nombre: 'Subvenciones, donaciones y legados a la explotación' },
    { codigo: '746', nombre: 'Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio' },
    { codigo: '747', nombre: 'Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio' },
    { codigo: '751', nombre: 'Resultados de operaciones en común' },
    { codigo: '752', nombre: 'Ingresos por arrendamientos' },
    { codigo: '753', nombre: 'Ingresos de propiedad industrial cedida en explotación' },
    { codigo: '754', nombre: 'Ingresos por comisiones' },
    { codigo: '755', nombre: 'Ingresos por servicios al personal' },
    { codigo: '759', nombre: 'Ingresos por servicios diversos' },
    { codigo: '760', nombre: 'Ingresos de participaciones en instrumentos de patrimonio' },
    { codigo: '761', nombre: 'Ingresos de valores representativos de deuda' },
    { codigo: '762', nombre: 'Ingresos de créditos' },
    { codigo: '763', nombre: 'Beneficios por valoración de activos y pasivos financieros por su valor razonable' },
    { codigo: '766', nombre: 'Beneficios en participaciones y valores representativos de deuda' },
    { codigo: '767', nombre: 'Ingresos de activos afectos y de derechos de reembolso relativos a retribuciones a largo plazo' },
    { codigo: '768', nombre: 'Diferencias positivas de cambio' },
    { codigo: '769', nombre: 'Otros ingresos financieros' },
    { codigo: '770', nombre: 'Beneficios procedentes del inmovilizado intangible' },
    { codigo: '771', nombre: 'Beneficios procedentes del inmovilizado material' },
    { codigo: '772', nombre: 'Beneficios procedentes de las inversiones inmobiliarias' },
    { codigo: '773', nombre: 'Beneficios procedentes de participaciones a largo plazo en partes vinculadas' },
    { codigo: '774', nombre: 'Diferencia negativa en combinaciones de negocios' },
    { codigo: '775', nombre: 'Beneficios por operaciones con obligaciones propias' },
    { codigo: '778', nombre: 'Ingresos excepcionales' },
    { codigo: '790', nombre: 'Reversión del deterioro del inmovilizado intangible' },
    { codigo: '791', nombre: 'Reversión del deterioro del inmovilizado material' },
    { codigo: '792', nombre: 'Reversión del deterioro de las inversiones inmobiliarias' },
    { codigo: '793', nombre: 'Reversión del deterioro de existencias' },
    { codigo: '794', nombre: 'Reversión del deterioro de créditos por operaciones comerciales' },
    { codigo: '795', nombre: 'Exceso de provisiones' },
    { codigo: '796', nombre: 'Reversión del deterioro de participaciones y valores representativos de deuda a largo plazo' },
    { codigo: '797', nombre: 'Reversión del deterioro de créditos a largo plazo' },
    { codigo: '798', nombre: 'Reversión del deterioro de participaciones y valores representativos de deuda a corto plazo' },
    { codigo: '799', nombre: 'Reversión del deterioro de créditos a corto plazo' }
];
